import fs from 'fs';

// 读取chinese-xinhua数据
const wordData = JSON.parse(fs.readFileSync('/Volumes/E/daima/zidian/chinese-xinhua/data/word.json', 'utf-8'));

// 转换汉字数据
const convertedWords = wordData.slice(0, 2000).map((item, index) => {
  const pinyinList = item.pinyin ? item.pinyin.split(',').map(p => p.trim()) : [];

  return {
    id: String(index + 1),
    character: item.word || '',
    pinyin: pinyinList,
    radical: item.radicals || '',
    strokes: parseInt(item.strokes) || 0,
    definition: item.explanation ? [item.explanation.substring(0, 200)] : [],
    phrases: [],
    idioms: [],
    synonyms: [],
    antonyms: [],
    examples: [],
    structure: '',
    etymology: '',
    partOfSpeech: []
  };
});

// 生成TypeScript文件
const output = `import type { Character } from '../types';

export const dictionary: Character[] = ${JSON.stringify(convertedWords, null, 2)};

export const radicals = [
  // 1画
  { id: '1', character: '一', strokes: 1 },
  { id: '2', character: '丨', strokes: 1 },
  { id: '3', character: '丿', strokes: 1 },
  { id: '4', character: '丶', strokes: 1 },
  { id: '5', character: '乙', strokes: 1 },
  // 2画
  { id: '6', character: '二', strokes: 2 },
  { id: '7', character: '十', strokes: 2 },
  { id: '8', character: '厂', strokes: 2 },
  { id: '9', character: '刂', strokes: 2 },
  { id: '10', character: '卜', strokes: 2 },
  { id: '11', character: '亻', strokes: 2 },
  { id: '12', character: '八', strokes: 2 },
  { id: '13', character: '人', strokes: 2 },
  { id: '14', character: '儿', strokes: 2 },
  { id: '15', character: '入', strokes: 2 },
  { id: '16', character: '冂', strokes: 2 },
  { id: '17', character: '冖', strokes: 2 },
  { id: '18', character: '冫', strokes: 2 },
  { id: '19', character: '几', strokes: 2 },
  { id: '20', character: '凵', strokes: 2 },
  { id: '21', character: '刀', strokes: 2 },
  { id: '22', character: '力', strokes: 2 },
  { id: '23', character: '勹', strokes: 2 },
  { id: '24', character: '匕', strokes: 2 },
  { id: '25', character: '匚', strokes: 2 },
  { id: '26', character: '卩', strokes: 2 },
  { id: '27', character: '厶', strokes: 2 },
  { id: '28', character: '又', strokes: 2 },
  // 3画
  { id: '29', character: '口', strokes: 3 },
  { id: '30', character: '囗', strokes: 3 },
  { id: '31', character: '土', strokes: 3 },
  { id: '32', character: '士', strokes: 3 },
  { id: '33', character: '夂', strokes: 3 },
  { id: '34', character: '夊', strokes: 3 },
  { id: '35', character: '夕', strokes: 3 },
  { id: '36', character: '大', strokes: 3 },
  { id: '37', character: '女', strokes: 3 },
  { id: '38', character: '子', strokes: 3 },
  { id: '39', character: '宀', strokes: 3 },
  { id: '40', character: '寸', strokes: 3 },
  { id: '41', character: '小', strokes: 3 },
  { id: '42', character: '尢', strokes: 3 },
  { id: '43', character: '尸', strokes: 3 },
  { id: '44', character: '屮', strokes: 3 },
  { id: '45', character: '山', strokes: 3 },
  { id: '46', character: '巛', strokes: 3 },
  { id: '47', character: '工', strokes: 3 },
  { id: '48', character: '己', strokes: 3 },
  { id: '49', character: '巾', strokes: 3 },
  { id: '50', character: '干', strokes: 3 },
  { id: '51', character: '幺', strokes: 3 },
  { id: '52', character: '广', strokes: 3 },
  { id: '53', character: '廴', strokes: 3 },
  { id: '54', character: '廾', strokes: 3 },
  { id: '55', character: '弋', strokes: 3 },
  { id: '56', character: '弓', strokes: 3 },
  { id: '57', character: '彐', strokes: 3 },
  { id: '58', character: '彡', strokes: 3 },
  { id: '59', character: '彳', strokes: 3 },
  // 4画
  { id: '60', character: '心', strokes: 4 },
  { id: '61', character: '忄', strokes: 4 },
  { id: '62', character: '戈', strokes: 4 },
  { id: '63', character: '戶', strokes: 4 },
  { id: '64', character: '手', strokes: 4 },
  { id: '65', character: '扌', strokes: 4 },
  { id: '66', character: '支', strokes: 4 },
  { id: '67', character: '攴', strokes: 4 },
  { id: '68', character: '文', strokes: 4 },
  { id: '69', character: '斗', strokes: 4 },
  { id: '70', character: '斤', strokes: 4 },
  { id: '71', character: '方', strokes: 4 },
  { id: '72', character: '无', strokes: 4 },
  { id: '73', character: '日', strokes: 4 },
  { id: '74', character: '曰', strokes: 4 },
  { id: '75', character: '月', strokes: 4 },
  { id: '76', character: '木', strokes: 4 },
  { id: '77', character: '欠', strokes: 4 },
  { id: '78', character: '止', strokes: 4 },
  { id: '79', character: '歹', strokes: 4 },
  { id: '80', character: '殳', strokes: 4 },
  { id: '81', character: '毋', strokes: 4 },
  { id: '82', character: '比', strokes: 4 },
  { id: '83', character: '毛', strokes: 4 },
  { id: '84', character: '氏', strokes: 4 },
  { id: '85', character: '气', strokes: 4 },
  { id: '86', character: '水', strokes: 4 },
  { id: '87', character: '氵', strokes: 4 },
  { id: '88', character: '火', strokes: 4 },
  { id: '89', character: '灬', strokes: 4 },
  { id: '90', character: '爪', strokes: 4 },
  { id: '91', character: '父', strokes: 4 },
  { id: '92', character: '爻', strokes: 4 },
  { id: '93', character: '爿', strokes: 4 },
  { id: '94', character: '片', strokes: 4 },
  { id: '95', character: '牙', strokes: 4 },
  { id: '96', character: '牛', strokes: 4 },
  { id: '97', character: '犭', strokes: 4 },
  { id: '98', character: '犬', strokes: 4 },
  // 5画及以上
  { id: '99', character: '玉', strokes: 5 },
  { id: '100', character: '王', strokes: 5 },
  { id: '101', character: '瓜', strokes: 5 },
  { id: '102', character: '瓦', strokes: 5 },
  { id: '103', character: '甘', strokes: 5 },
  { id: '104', character: '生', strokes: 5 },
  { id: '105', character: '用', strokes: 5 },
  { id: '106', character: '田', strokes: 5 },
  { id: '107', character: '疋', strokes: 5 },
  { id: '108', character: '疒', strokes: 5 },
  { id: '109', character: '癶', strokes: 5 },
  { id: '110', character: '白', strokes: 5 },
  { id: '111', character: '皮', strokes: 5 },
  { id: '112', character: '皿', strokes: 5 },
  { id: '113', character: '目', strokes: 5 },
  { id: '114', character: '矛', strokes: 5 },
  { id: '115', character: '矢', strokes: 5 },
  { id: '116', character: '石', strokes: 5 },
  { id: '117', character: '示', strokes: 5 },
  { id: '118', character: '禸', strokes: 5 },
  { id: '119', character: '禾', strokes: 5 },
  { id: '120', character: '穴', strokes: 5 },
  { id: '121', character: '立', strokes: 5 },
  { id: '122', character: '竹', strokes: 6 },
  { id: '123', character: '米', strokes: 6 },
  { id: '124', character: '糸', strokes: 6 },
  { id: '125', character: '缶', strokes: 6 },
  { id: '126', character: '网', strokes: 6 },
  { id: '127', character: '羊', strokes: 6 },
  { id: '128', character: '羽', strokes: 6 },
  { id: '129', character: '老', strokes: 6 },
  { id: '130', character: '而', strokes: 6 },
  { id: '131', character: '耒', strokes: 6 },
  { id: '132', character: '耳', strokes: 6 },
  { id: '133', character: '聿', strokes: 6 },
  { id: '134', character: '肉', strokes: 6 },
  { id: '135', character: '臣', strokes: 6 },
  { id: '136', character: '自', strokes: 6 },
  { id: '137', character: '至', strokes: 6 },
  { id: '138', character: '臼', strokes: 6 },
  { id: '139', character: '舌', strokes: 6 },
  { id: '140', character: '舛', strokes: 6 },
  { id: '141', character: '舟', strokes: 6 },
  { id: '142', character: '艮', strokes: 6 },
  { id: '143', character: '色', strokes: 6 },
  { id: '144', character: '艸', strokes: 6 },
  { id: '145', character: '虍', strokes: 6 },
  { id: '146', character: '虫', strokes: 6 },
  { id: '147', character: '血', strokes: 6 },
  { id: '148', character: '行', strokes: 6 },
  { id: '149', character: '衣', strokes: 6 },
  { id: '150', character: '襾', strokes: 6 },
  { id: '151', character: '见', strokes: 7 },
  { id: '152', character: '角', strokes: 7 },
  { id: '153', character: '言', strokes: 7 },
  { id: '154', character: '讠', strokes: 7 },
  { id: '155', character: '谷', strokes: 7 },
  { id: '156', character: '豆', strokes: 7 },
  { id: '157', character: '豕', strokes: 7 },
  { id: '158', character: '豸', strokes: 7 },
  { id: '159', character: '贝', strokes: 7 },
  { id: '160', character: '赤', strokes: 7 },
  { id: '161', character: '走', strokes: 7 },
  { id: '162', character: '足', strokes: 7 },
  { id: '163', character: '身', strokes: 7 },
  { id: '164', character: '车', strokes: 7 },
  { id: '165', character: '辛', strokes: 7 },
  { id: '166', character: '辰', strokes: 7 },
  { id: '167', character: '辵', strokes: 7 },
  { id: '168', character: '邑', strokes: 7 },
  { id: '169', character: '酉', strokes: 7 },
  { id: '170', character: '釆', strokes: 7 },
  { id: '171', character: '里', strokes: 7 },
  { id: '172', character: '金', strokes: 8 },
  { id: '173', character: '钅', strokes: 8 },
  { id: '174', character: '长', strokes: 8 },
  { id: '175', character: '门', strokes: 8 },
  { id: '176', character: '阜', strokes: 8 },
  { id: '177', character: '隶', strokes: 8 },
  { id: '178', character: '隹', strokes: 8 },
  { id: '179', character: '雨', strokes: 8 },
  { id: '180', character: '青', strokes: 8 },
  { id: '181', character: '非', strokes: 8 },
  { id: '182', character: '面', strokes: 9 },
  { id: '183', character: '革', strokes: 9 },
  { id: '184', character: '韦', strokes: 9 },
  { id: '185', character: '韭', strokes: 9 },
  { id: '186', character: '音', strokes: 9 },
  { id: '187', character: '页', strokes: 9 },
  { id: '188', character: '风', strokes: 9 },
  { id: '189', character: '飞', strokes: 9 },
  { id: '190', character: '食', strokes: 9 },
  { id: '191', character: '饣', strokes: 9 },
  { id: '192', character: '首', strokes: 9 },
  { id: '193', character: '香', strokes: 9 },
  { id: '194', character: '马', strokes: 10 },
  { id: '195', character: '骨', strokes: 10 },
  { id: '196', character: '高', strokes: 10 },
  { id: '197', character: '髟', strokes: 10 },
  { id: '198', character: '鬥', strokes: 10 },
  { id: '199', character: '鬯', strokes: 10 },
  { id: '200', character: '鬲', strokes: 10 },
  { id: '201', character: '鬼', strokes: 10 },
  { id: '202', character: '鱼', strokes: 11 },
  { id: '203', character: '鸟', strokes: 11 },
  { id: '204', character: '鹵', strokes: 11 },
  { id: '205', character: '鹿', strokes: 11 },
  { id: '206', character: '麦', strokes: 11 },
  { id: '207', character: '麻', strokes: 11 },
  { id: '208', character: '黄', strokes: 12 },
  { id: '209', character: '黍', strokes: 12 },
  { id: '210', character: '黑', strokes: 12 },
  { id: '211', character: '黹', strokes: 12 },
  { id: '212', character: '黽', strokes: 13 },
  { id: '213', character: '鼓', strokes: 13 },
  { id: '214', character: '鼠', strokes: 13 }
];
`;

fs.writeFileSync('/Volumes/E/daima/zidian/zidian/src/data/dictionary.ts', output, 'utf-8');
console.log('数据转换完成！已生成2000个汉字数据');
